# Generated by Django 5.1.6 on 2025-07-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_item_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image',
            new_name='image',
        ),
    ]
