# Generated by Django 5.1.6 on 2025-07-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_rename_item_image_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='item_image',
        ),
    ]
